#! /bin/bash
lscpu
echo ""
echo ""
echo ""
echo "Compilation starts..."
g++ int.cpp -O3 -o gcc_int.elf
g++ float.cpp -O3 -o gcc_float.elf
g++ sha256.cpp sha256_main.cpp -O3 -o gcc_sha256.elf
clang++ int.cpp -O3 -o clang_int.elf
clang++ float.cpp -O3 -o clang_float.elf
clang++ sha256.cpp sha256_main.cpp -O3 -o clang_sha256.elf
echo "Done!"
echo ""
echo ""

echo "---GCC compiled---"
echo ""

echo "Integers:"
time -p ./gcc_int.elf
echo ""
echo "Floats:"
time -p ./gcc_float.elf
echo ""
echo "SHA256:"
time -p ./gcc_sha256.elf

echo ""
echo ""
echo ""
echo "---Clang compiled---"
echo ""
echo "Integers:"
time -p ./clang_int.elf
echo ""
echo "Floats:"
time -p ./clang_float.elf
echo ""
echo "SHA256:"
time -p ./clang_sha256.elf



echo ""
echo ""
echo ""
echo "Done! Anykey to exit..."

read
