#! /bin/bash
lscpu
echo ""
echo ""
echo ""
echo "Compilation stared..."

g++ float.cpp -O3 -o gcc_float.elf
g++ long.cpp -O3 -o gcc_long.elf
g++ long_double.cpp -O3 -o gcc_long_double.elf
g++ int.cpp -o gcc_int.elf
g++ sha256.cpp sha256_main.cpp -O3 -o gcc_sha256.elf

clang++ float.cpp -O3 -o clang_float.elf
clang++ long.cpp -O3 -o clang_long.elf
clang++ long_double.cpp -O3 -o clang_long_double.elf
clang++ int.cpp -o clang_int.elf
clang++ sha256.cpp sha256_main.cpp -O3 -o clang_sha256.elf

echo "Done!"
echo ""
echo ""

echo "---GCC compiled---"
echo ""
echo "division of float (32bit):"
time -p ./gcc_float.elf
echo ""
echo "division of long (64bit):"
time -p ./gcc_long.elf
echo ""
echo "division of long double (80 bit):"
time -p ./gcc_long_double.elf
echo ""
echo "addition of integers:"
time -p ./gcc_int.elf
echo ""
echo "SHA256:"
time -p ./gcc_sha256.elf

echo ""
echo ""
echo ""

echo "---Clang compiled---"
echo ""
echo "division of float (32bit):"
time -p ./clang_float.elf
echo ""
echo "division of long (64bit):"
time -p ./clang_long.elf
echo ""
echo "division of long double (80 bit):"
time -p ./clang_long_double.elf
echo ""
echo "addition of integers:"
time -p ./clang_int.elf
echo ""
echo "SHA256:"
time -p ./clang_sha256.elf

echo ""
echo ""
echo ""
echo "Do anykey to exit..."

read
